### ISSUE TITLE
[Bug] fps is inf

### ISSUE THREAD

**Issue by UpCoder** [MKLab-ITI/intermediate-cnn-features#8]
I found there are some special case in CCWEBVideos whose fps is inf. 
So the load_video only return the first frame. 
I think this [line](https://github.com/MKLab-ITI/intermediate-cnn-features/blob/68d3042abc81d3f6a808592c113f1c4882e5268c/utils.py#L38) can be replaced by 
```python
if not fps or fps != fps or fps == np.inf:
```

**Comment by gkordo** [comment]
Thank you for your contribution. I have updated the code as you suggested.
